name: t_store
description: "A new Flutter project."
 
 
publish_to: 'none'  

 
 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


# PACKAGES
dependencies:
  flutter:
    sdk: flutter

#  UTILITY PACKAGES
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0

#  ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

#  STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.14.0
  lottie: ^3.3.1
#  connectivity_plus: ^6.1.4
  connectivity_plus: ^4.0.2
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.1.0



#  PRODUCT SPECIFIC


#PACKEAGES END

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
#app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/app_icon/app_icon.png



  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#LOCAL ASSETS
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/onboarding/
    - assets/images/popular_categories/
    - assets/images/banner/
    - assets/images/email/
    - assets/images/app_icon/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/payment/
    - assets/animation/
    - assets/images/login/


#  fonts:
#    - family: Poppins
#      fonts:
#        -asset: assets/fonts/Poppins-Black.ttf

   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
