name: t_store
description: "A new Flutter project."
 
 
publish_to: 'none'  

 
 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


# PACKAGES
dependencies:
  flutter:
    sdk: flutter

#  UTILITY PACKAGES
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1

#  ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

#  STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1


#  PRODUCT SPECIFIC


#PACKEAGES END

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#LOCAL ASSETS
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/onboarding/

#  fonts:
#    - family: Poppins
#      fonts:
#        -asset: assets/fonts/Poppins-Black.ttf

   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
