// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilWrIp36XS7pmoD-S1GhfYpJWNls1tBs',
    appId: '1:177282155559:android:fbadea735b666d798a3a02',
    messagingSenderId: '177282155559',
    projectId: 'storeapp-97bde',
    storageBucket: 'storeapp-97bde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Xkzf8RwipkjDegPvS5_sznMhVBi3xwM',
    appId: '1:177282155559:ios:bfc0b88407a6c6148a3a02',
    messagingSenderId: '177282155559',
    projectId: 'storeapp-97bde',
    storageBucket: 'storeapp-97bde.firebasestorage.app',
    androidClientId: '177282155559-epqvd15iul2sbnmeek5k306fiaij4m7j.apps.googleusercontent.com',
    iosClientId: '177282155559-koglmiiq03ebs129i8bs6tsu0fkd5l5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}